name: Build Flet APK

on: [push]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Flet
        run: pip install flet
        
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.22.0'
          
      - name: Setup Android SDK (safe method)
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip -q commandlinetools-linux-10406996_latest.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:$HOME/android-sdk/cmdline-tools/latest:$HOME/android-sdk/platform-tools" >> $GITHUB_ENV
        if: ${{ !env.ANDROID_HOME }}
        
      - name: Install Android components
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0" "ndk;25.2.9519653"
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          
      - name: Accept Flutter licenses
        run: flutter doctor --android-licenses -y
        
      - name: Build APK
        run: flet build apk --python main.py
        
      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/apk/release/app-release.apk
