name: Build Flet APK

on: [push]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install flet

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.29.2'

      - name: Install Android dependencies
        run: sudo apt-get install -y libgtk-3-dev unzip

      - name: Verify project structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in repository:"
          ls -la
          echo "Looking for Python files:"
          find . -name "*.py"

      - name: Build APK with explicit module name
        run: |
          # Создаем временный entrypoint.py в корне
          cat > entrypoint.py <<EOF
          import sys
          sys.path.insert(0, 'src')
          from main import main
          
          if __name__ == '__main__':
              main()
          EOF
          
          # Собираем APK
          flet build apk entrypoint.py

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/apk/release/app-release.apk
