name: Build Flet APK

on: [push]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Python dependencies
        run: pip install flet
          
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          
      - name: Accept Android licenses
        run: |
          yes | sdkmanager --licenses || true
          flutter doctor --android-licenses -y
          
      - name: Install system dependencies
        run: sudo apt-get install -y clang cmake ninja-build libgtk-3-dev
          
      - name: Build APK
        run: flet build apk --python main.py
        
      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/apk/release/app-release.apk
